# Generated by Django 4.2.3 on 2023-07-05 22:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
