# Generated by Django 4.2.3 on 2023-10-04 18:44

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
